### ISSUE TITLE
Error in logs when temp / humidity are unavailable

### ISSUE THREAD

**Issue by elad-bar** [Strixx76/mold_risk_index#4]
Although is handling well unavailailbility of entities attached to it, since last version of HA, logs are getting filled with logs (below), reason states are reported as `unknown` which is not valid type (string) while the expectation is for a numeric / None,
I change the code locally and it solve that issue, but essentially, need to use whatever reported from the mold risk calculator even if it is None, HA will translate it to unknown by itself.

```log
06/10/2023 2:20:12 PM
During handling of the above exception, another exception occurred:
06/10/2023 2:20:12 PM
06/10/2023 2:20:12 PM
Traceback (most recent call last):
06/10/2023 2:20:12 PM
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 581, in state
06/10/2023 2:20:12 PM
    numerical_value = int(value)
06/10/2023 2:20:12 PM
                      ^^^^^^^^^^
06/10/2023 2:20:12 PM
ValueError: invalid literal for int() with base 10: 'unknown'
06/10/2023 2:20:12 PM
06/10/2023 2:20:12 PM
The above exception was the direct cause of the following exception:
06/10/2023 2:20:12 PM
06/10/2023 2:20:12 PM
Traceback (most recent call last):
06/10/2023 2:20:12 PM
  File "/usr/local/lib/python3.11/logging/handlers.py", line 1498, in emit
06/10/2023 2:20:12 PM
    self.enqueue(self.prepare(record))
06/10/2023 2:20:12 PM
                 ^^^^^^^^^^^^^^^^^^^^
06/10/2023 2:20:12 PM
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 44, in prepare
06/10/2023 2:20:12 PM
    record = super().prepare(record)
06/10/2023 2:20:12 PM
             ^^^^^^^^^^^^^^^^^^^^^^^
06/10/2023 2:20:12 PM
  File "/usr/local/lib/python3.11/logging/handlers.py", line 1480, in prepare
06/10/2023 2:20:12 PM
    msg = self.format(record)
06/10/2023 2:20:12 PM
          ^^^^^^^^^^^^^^^^^^^
06/10/2023 2:20:12 PM
  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
06/10/2023 2:20:12 PM
    return fmt.format(record)
06/10/2023 2:20:12 PM
           ^^^^^^^^^^^^^^^^^^
06/10/2023 2:20:12 PM
  File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
06/10/2023 2:20:12 PM
    record.message = record.getMessage()
06/10/2023 2:20:12 PM
                     ^^^^^^^^^^^^^^^^^^^
06/10/2023 2:20:12 PM
  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
06/10/2023 2:20:12 PM
    msg = msg % self.args
06/10/2023 2:20:12 PM
          ~~~~^~~~~~~~~~~
06/10/2023 2:20:12 PM
  File "/usr/src/homeassistant/homeassistant/core.py", line 253, in __repr__
06/10/2023 2:20:12 PM
    return f"<Job {self.name} {self.job_type} {self.target}>"
06/10/2023 2:20:12 PM
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
06/10/2023 2:20:12 PM
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 677, in __repr__
06/10/2023 2:20:12 PM
    return super().__repr__()
06/10/2023 2:20:12 PM
           ^^^^^^^^^^^^^^^^^^
06/10/2023 2:20:12 PM
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1026, in __repr__
06/10/2023 2:20:12 PM
    return f"<entity {self.entity_id}={self._stringify_state(self.available)}>"
06/10/2023 2:20:12 PM
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
06/10/2023 2:20:12 PM
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
06/10/2023 2:20:12 PM
    if (state := self.state) is None:
06/10/2023 2:20:12 PM
                 ^^^^^^^^^^
06/10/2023 2:20:12 PM
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
06/10/2023 2:20:12 PM
    raise ValueError(
06/10/2023 2:20:12 PM
ValueError: Sensor sensor.roni_s_room_mold_risk_index_risk_index has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>)
```

**Comment by Strixx76** [comment]
New release out now. Thank you for the fix.

**Comment by elad-bar** [comment]
Thanks!
